---
- name: Install all security updates with automatic reboots
  hosts: all
  gather_facts: false
  tasks:
    - name: Install all security updates with automatic reboots
      win_updates:
        category_names:
        - SecurityUpdates
        - Updates
        reboot: yes
